

export_helm_config:
	export HELM_NAME=$(HELM_NAME)
	export HELM_NAMESPACE=$(HELM_NAMESPACE)
	export HELM_RELEASE_NAME=$(HELM_RELEASE_NAME)
	export HELM_VERSION=$(HELM_VERSION)
	export HELM_REPO=$(HELM_REPO)

export_overlay_config:
	export OVERLAY_APP_NAME=$(OVERLAY_APP_NAME)
	export OVERLAY_USER_GIVEN_NAME=$(OVERLAY_USER_GIVEN_NAME)
	export OVERLAY_DEST_NAMESPACE=$(OVERLAY_DEST_NAMESPACE)
	export OVERLAY_DEST_SERVER=$(OVERLAY_DEST_SERVER)
	export OVERLAY_SRC_PATH=$(OVERLAY_SRC_PATH)
	export OVERLAY_SRC_REPO_URL=$(OVERLAY_SRC_REPO_URL)

generate_helm: export_helm_config
	echo $@
	echo $^
